<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created At' => 'Создан',
    'Error Save Model.' => 'Ошибка сохранения модели',
    'Error upload File. {message}' => 'Ошибка загрузки файла. {message}',
    'Files attachments' => 'Вложения',
    'Files uploaded' => 'Файлы загружены',
    'Home' => 'Главная',
    'ID' => 'ИД',
    'Images' => 'Изображения',
    'Images List' => 'Список изображений',
    'Name' => 'Имя',
    'Preview' => 'Превью',
    'The maximum file size is more than {max_files_size} MB' => 'Максимальный размер файла превышает {max_files_size} МБ.',
    'Upload' => 'Загрузить',
    'Upload Files' => 'Загрузить файлы',
];
